[pytest]
pythonpath = .
filterwarnings =
    ignore::pyparsing.PyparsingDeprecationWarning:matplotlib.*
    ignore::DeprecationWarning:matplotlib.*
    ignore::matplotlib.MatplotlibDeprecationWarning
